# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quick Recipes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quick Recipes

  target 'Quick RecipesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Quick RecipesUITests' do
    # Pods for testing
  end

 pod 'RealmSwift'

end
